### ISSUE TITLE
¿Cómo ayudar?

### ISSUE THREAD

**Issue by TresErres** [montogeek/laravel-docs-es#11]
Pues eso, ¿cómo comienzo a ayudar? ¿Cómo hacer para no duplicar el trabajo?
Por ejemplo, ¿traduzco eloquent?

**Comment by dmaciasSS** [comment]
Misma pregunta que la mia, pasa los datos para ayudar.

**Comment by montogeek** [comment]
Hola!

Simplemente traduzcan las paginas que no estan traducidas, pueden abrir un Issue antes y asi otra persona sabra que se esta traduciendo y que no.

Gracias!

**Comment by dmaciasSS** [comment]
Quieres un pull request?

**Comment by montogeek** [comment]
Si, es la mejor forma
