### ISSUE TITLE
Agregar la versión 5.1 y ayudare. 

### ISSUE THREAD

**Issue by jartaud** [montogeek/laravel-docs-es#20]
También sería bueno poder implementar algo como un indicador de progreso. Eso nos permitiría saber que archivo traducir sin tener que navegar en toda la documentación.

**Comment by montogeek** [comment]
Hola @jartaud, ya agregue la version 5.1 al repositorio, corresponde al branch `master` y en #21 se estará actualizando el avance de la traduccion.

Gracias por participar!
