### ISSUE TITLE
Avance traduccion 5.1 

### ISSUE THREAD

**Issue by montogeek** [montogeek/laravel-docs-es#21]
Avance de la traduccion de Laravel 5.1
- [x] Artisan (https://github.com/montogeek/laravel-docs-es/pull/22)
- [ ] Authentication (En progreso)
- [ ] Billing
- [ ] Blade
- [ ] Cache
- [ ] Collections
- [ ] Container
- [ ] Contracts
- [ ] Contributing
- [ ] Contributions
- [ ] Controllers
- [ ] Database
- [ ] Documentation
- [ ] Elixir
- [ ] Eloquent-collections
- [ ] Eloquent-mutators
- [ ] Eloquent-relationships
- [ ] Eloquent-serialization
- [ ] Eloquent
- [ ] Encryption
- [ ] Envoy
- [ ] Errors
- [ ] Events
- [ ] Facades
- [ ] Filesystem
- [ ] Hashing
- [ ] Helpers
- [ ] Homestead
- [x] Installation (https://github.com/montogeek/laravel-docs-es/pull/23)
- [ ] License
- [ ] Lifecycle
- [ ] Localization
- [ ] Mail
- [ ] Middleware
- [ ] Migrations
- [ ] Packages
- [ ] Pagination
- [ ] Providers
- [ ] Queries
- [ ] Queues
- [ ] Readme
- [ ] Redis
- [ ] Releases
- [ ] Requests
- [ ] Responses
- [ ] Routing
- [ ] Scheduling
- [ ] Seeding
- [ ] Session
- [ ] Structure
- [ ] Testing
- [ ] Upgrade
- [ ] Validation
- [ ] Views

**Comment by zeratulmdq** [comment]
¿Siguen en pie con esta traducción? Si es así, empiezo a ayudar.

**Comment by montogeek** [comment]
Claro que si @zeratulmdq 
Empieza con el que quieras :)
